apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-app
  template:
    metadata:
      labels:
        app: auto-app
    spec:
      containers:
        - name: auto-app
          image: prathvishs/q10
          ports:
            - containerPort: 3000
